project_id = "wgerdrdsuusnrdnwwelt"

[functions.reserve_and_execute]
verify_jwt = false

[functions.renewal-reminder]
verify_jwt = false

[functions.admin-search-users]
verify_jwt = true

[functions.admin-adjust-credits]
verify_jwt = true