
import { CreativeCharacterData } from '../types/creativeCharacterTypes';

export class CreativeCharacterConversationParser {
  /**
   * Parses a compiled character description and extracts CreativeCharacterData
   */
  static parseCharacterDescription(description: string): CreativeCharacterData {
    console.log('Parsing character description:', description);

    // Extract key information using patterns and keywords
    const name = this.extractName(description);
    const entityType = this.extractEntityType(description);
    const narrativeDomain = this.extractNarrativeDomain(description);
    const environment = this.extractEnvironment(description);
    const physicalForm = this.extractPhysicalForm(description);
    const communication = this.extractCommunication(description);
    const surfaceTriggers = this.extractSurfaceTriggers(description);

    const characterData: CreativeCharacterData = {
      name: name || 'Unnamed Character',
      entityType: entityType,
      narrativeDomain: narrativeDomain,
      functionalRole: this.extractFunctionalRole(description),
      description: description,
      environment: environment,
      physicalForm: physicalForm,
      communication: communication,
      coreDrives: [], // Will be generated by the trait architecture builder
      surfaceTriggers: surfaceTriggers,
      changeResponseStyle: this.extractChangeResponseStyle(description)
    };

    console.log('Parsed character data:', characterData);
    return characterData;
  }

  private static extractName(description: string): string {
    // Look for name patterns
    const namePatterns = [
      /(?:named?|called?)\s+([A-Z][a-zA-Z]+)/i,
      /^([A-Z][a-zA-Z]+)\s+is/,
      /Character:?\s*([A-Z][a-zA-Z]+)/i,
      /Name:?\s*([A-Z][a-zA-Z]+)/i
    ];

    for (const pattern of namePatterns) {
      const match = description.match(pattern);
      if (match && match[1]) {
        return match[1].trim();
      }
    }

    return '';
  }

  private static extractEntityType(description: string): string {
    const desc = description.toLowerCase();
    
    // Check for specific entity type indicators
    if (desc.includes('coil') || desc.includes('crystalline') || 
        desc.includes('translucent') || desc.includes('vapor') ||
        desc.includes('energy being') || desc.includes('fluid') ||
        desc.includes('non-humanoid') || desc.includes('alien') ||
        desc.includes('creature') || desc.includes('entity')) {
      return 'non_humanoid';
    }
    
    if (desc.includes('post-biological') || desc.includes('consciousness') ||
        desc.includes('digital') || desc.includes('ai')) {
      return 'post_biological';
    }
    
    if (desc.includes('human') || desc.includes('person') || desc.includes('character')) {
      return 'human';
    }
    
    // Default to non_humanoid for creative characters
    return 'non_humanoid';
  }

  private static extractNarrativeDomain(description: string): string {
    const desc = description.toLowerCase();
    
    if (desc.includes('sci-fi') || desc.includes('science fiction') || 
        desc.includes('space') || desc.includes('future') || 
        desc.includes('technology') || desc.includes('cyberpunk')) {
      return 'sci-fi';
    }
    
    if (desc.includes('fantasy') || desc.includes('magic') || 
        desc.includes('medieval') || desc.includes('dragon') ||
        desc.includes('wizard') || desc.includes('enchanted')) {
      return 'fantasy';
    }
    
    if (desc.includes('horror') || desc.includes('dark') || 
        desc.includes('scary') || desc.includes('creepy')) {
      return 'horror';
    }
    
    if (desc.includes('surreal') || desc.includes('abstract') || 
        desc.includes('dream') || desc.includes('bizarre')) {
      return 'surreal';
    }
    
    if (desc.includes('modern') || desc.includes('contemporary') || 
        desc.includes('present day')) {
      return 'modern';
    }
    
    // Default to surreal for creative characters
    return 'surreal';
  }

  private static extractEnvironment(description: string): string {
    // Extract physical/environmental descriptions
    const envPatterns = [
      /(?:appears?|looks?|manifests?)\s+(?:as\s+)?([^.!?]+)/i,
      /(?:physical|appearance|form):?\s*([^.!?]+)/i,
      /(?:body|structure|shape):?\s*([^.!?]+)/i
    ];

    for (const pattern of envPatterns) {
      const match = description.match(pattern);
      if (match && match[1]) {
        return match[1].trim();
      }
    }

    return description.slice(0, 200) + '...'; // Fallback to first part of description
  }

  private static extractPhysicalForm(description: string): string {
    const desc = description.toLowerCase();
    
    if (desc.includes('massive') || desc.includes('giant') || desc.includes('large')) {
      return 'Large scale entity';
    }
    
    if (desc.includes('tiny') || desc.includes('small') || desc.includes('miniature')) {
      return 'Small scale entity';
    }
    
    if (desc.includes('human-sized') || desc.includes('person')) {
      return 'Human-sized';
    }
    
    return 'Variable or undefined scale';
  }

  private static extractCommunication(description: string): string {
    const desc = description.toLowerCase();
    
    if (desc.includes('bioluminescent') || desc.includes('glowing') || 
        desc.includes('light') || desc.includes('pulse')) {
      return 'Bioluminescent pulses';
    }
    
    if (desc.includes('telepathic') || desc.includes('psychic') || 
        desc.includes('mind') || desc.includes('thought')) {
      return 'Telepathic communication';
    }
    
    if (desc.includes('speak') || desc.includes('voice') || desc.includes('talk')) {
      return 'Verbal communication';
    }
    
    if (desc.includes('gesture') || desc.includes('movement') || desc.includes('dance')) {
      return 'Gestural communication';
    }
    
    return 'Undefined communication method';
  }

  private static extractSurfaceTriggers(description: string): string[] {
    const triggers: string[] = [];
    const desc = description.toLowerCase();
    
    // Common trigger patterns
    if (desc.includes('pattern') || desc.includes('order') || desc.includes('structure')) {
      triggers.push('Pattern recognition');
    }
    
    if (desc.includes('chaos') || desc.includes('disorder') || desc.includes('disruption')) {
      triggers.push('System disruption');
    }
    
    if (desc.includes('resonance') || desc.includes('harmony') || desc.includes('alignment')) {
      triggers.push('Harmonic resonance');
    }
    
    if (desc.includes('threat') || desc.includes('danger') || desc.includes('protective')) {
      triggers.push('Threat detection');
    }
    
    return triggers.length > 0 ? triggers : ['Undefined triggers'];
  }

  private static extractFunctionalRole(description: string): string {
    const desc = description.toLowerCase();
    
    if (desc.includes('guardian') || desc.includes('protector') || desc.includes('defender')) {
      return 'guardian_entity';
    }
    
    if (desc.includes('oracle') || desc.includes('seer') || desc.includes('prophet')) {
      return 'oracle_interpreter';
    }
    
    if (desc.includes('ritual') || desc.includes('ceremony') || desc.includes('sacred')) {
      return 'ritual_coordinator';
    }
    
    if (desc.includes('guide') || desc.includes('navigator') || desc.includes('dimension')) {
      return 'dimensional_navigator';
    }
    
    return 'undefined_role';
  }

  private static extractChangeResponseStyle(description: string): string {
    const desc = description.toLowerCase();
    
    if (desc.includes('adapt') || desc.includes('flexible') || desc.includes('evolve')) {
      return 'mutate_adapt';
    }
    
    if (desc.includes('collapse') || desc.includes('withdraw') || desc.includes('destabilize')) {
      return 'collapse_destabilize';
    }
    
    if (desc.includes('suppress') || desc.includes('resist') || desc.includes('contradict')) {
      return 'suppress_contradiction';
    }
    
    return 'mutate_adapt'; // Default
  }
}
