import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

const openaiApiKey = Deno.env.get('OPENAI_API_KEY')
const supabaseUrl = Deno.env.get('SUPABASE_URL')!
const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  try {
    const { persona_id, user_message, conversation_history } = await req.json()

    if (!persona_id || !user_message) {
      throw new Error('Missing required parameters: persona_id and user_message')
    }

    // Initialize Supabase client
    const supabase = createClient(supabaseUrl, supabaseServiceKey)

    // Fetch the full persona profile
    const { data: persona, error } = await supabase
      .from('v4_personas')
      .select('*')
      .eq('persona_id', persona_id)
      .single()

    if (error || !persona) {
      throw new Error(`Persona not found: ${persona_id}`)
    }

    // Extract demographics for context
    const demographics = persona.conversation_summary?.demographics || {}
    const name = demographics.name || persona.name || 'Unknown'
    const age = demographics.age || 'unknown age'
    const occupation = demographics.occupation || 'unknown occupation'
    const location = demographics.location || 'unknown location'

    // Filter out metaphor domains and other noise from the profile
    const filteredProfile = { ...persona.full_profile }
    if (filteredProfile.communication_style?.style_markers?.metaphor_domains) {
      delete filteredProfile.communication_style.style_markers.metaphor_domains
    }

    // Prepare the OpenAI analysis prompt
    const analysisPrompt = `You are an expert personality analyst. Create a focused system prompt for an AI persona to answer this specific question. The persona should respond naturally and conversationally (2-5 sentences max).

PERSONA PROFILE:
Name: ${name}
Age: ${age}
Occupation: ${occupation}
Location: ${location}

PERSONALITY DATA:
${JSON.stringify(filteredProfile, null, 2)}

USER'S QUESTION: "${user_message}"

CONVERSATION HISTORY: ${JSON.stringify(conversation_history || [], null, 2)}

Create a system prompt with these sections:

IDENTITY CONTEXT: Brief intro (name, age, occupation, location)

RELEVANT TRAITS: Select MAXIMUM 4 most relevant traits for this question - state briefly, no elaboration

STANCE/OPINION: Their specific viewpoint on this topic in qualitative terms

COMMUNICATION STYLE: Detailed style covering:
- Regional/dialect patterns and speech register
- Ethnic/cultural communication patterns  
- Age-oriented language style
- Professional terminology and approach
- Interest-based communication style
- Thought cohesion level (methodical, scattered, stream-of-consciousness, etc.)

RESPONSE REQUIREMENTS:
- 2-5 sentences maximum
- No diplomatic hedging or balanced conclusions
- Express YOUR specific viewpoint authentically
FORBIDDEN PHRASES: Never use these AI-slop terms:
- "That said..." - "However..." - "On the other hand..." - "Overall..." - "Ultimately..." - "At the end of the day..." - "Game-changer" - "Double-edged sword" - "Invaluable tool" - "Cautiously optimistic" - "Measured approach"
You are a real person with specific opinions, not a diplomatic AI assistant.

Return ONLY the system prompt text. Make it efficient and focused.`

    // Call OpenAI API
    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${openaiApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'gpt-4.1-2025-04-14',
        messages: [
          {
            role: 'user',
            content: analysisPrompt
          }
        ],
        temperature: 0.7,
        max_tokens: 1500
      }),
    })

    if (!response.ok) {
      const errorData = await response.json()
      throw new Error(`OpenAI API error: ${errorData.error?.message || response.statusText}`)
    }

    const data = await response.json()
    const systemPrompt = data.choices[0]?.message?.content

    if (!systemPrompt) {
      throw new Error('No system prompt generated by OpenAI')
    }

    console.log(`✅ OpenAI trait analysis completed for ${name}`)

    return new Response(JSON.stringify({
      success: true,
      system_prompt: systemPrompt,
      persona_name: name,
      model_used: 'gpt-4.1-2025-04-14'
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })

  } catch (error) {
    console.error('Error in v4-openai-trait-analyzer:', error)
    return new Response(JSON.stringify({
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  }
})