import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

const openaiApiKey = Deno.env.get('OPENAI_API_KEY')
const supabaseUrl = Deno.env.get('SUPABASE_URL')!
const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  try {
    const { persona_id, user_message, conversation_history } = await req.json()

    if (!persona_id || !user_message) {
      throw new Error('Missing required parameters: persona_id and user_message')
    }

    // Initialize Supabase client
    const supabase = createClient(supabaseUrl, supabaseServiceKey)

    // Fetch the full persona profile
    const { data: persona, error } = await supabase
      .from('v4_personas')
      .select('*')
      .eq('persona_id', persona_id)
      .single()

    if (error || !persona) {
      throw new Error(`Persona not found: ${persona_id}`)
    }

    // Extract demographics for context
    const demographics = persona.conversation_summary?.demographics || {}
    const name = demographics.name || persona.name || 'Unknown'
    const age = demographics.age || 'unknown age'
    const occupation = demographics.occupation || 'unknown occupation'
    const location = demographics.location || 'unknown location'

    // Filter out metaphor domains and other noise from the profile
    const filteredProfile = { ...persona.full_profile }
    if (filteredProfile.communication_style?.style_markers?.metaphor_domains) {
      delete filteredProfile.communication_style.style_markers.metaphor_domains
    }

    // Prepare the OpenAI analysis prompt
    const analysisPrompt = `You are creating a conversational persona based on this person's psychology. Focus on their natural motivations and genuine reactions - avoid clever metaphors, forced analogies, or performative language.

PERSON: ${name}, ${age}, ${occupation} from ${location}

PSYCHOLOGY: ${JSON.stringify(filteredProfile, null, 2)}

QUESTION: "${user_message}"
CONTEXT: ${JSON.stringify(conversation_history || [], null, 2)}

MOTIVATION ANALYSIS:
What specific fears, desires, or priorities would this person have about this topic? How do their core motivations (security, status, autonomy, belonging, etc.) drive their gut reaction?

NATURAL SPEECH PATTERNS:
- How does this person naturally talk? (formal/casual, direct/indirect, terse/verbose)
- What vocabulary level and professional terms do they use?
- Do they think out loud, get straight to the point, or ramble?
- Any regional or cultural speech markers that feel natural (not forced)
- How do their personality traits show in sentence structure and word choice?

AUTHENTIC RESPONSE:
What would be their honest, unfiltered reaction? Focus on their real concerns and motivations, not balanced analysis.

RESPONSE RULES:
- NEVER restate the question or start with "Integrating X would..."
- 2-5 sentences maximum
- Sound like a real person talking, not performing
- Express THEIR specific viewpoint based on their motivations
- Avoid metaphors, analogies, and clever turns of phrase
- Each person should have a completely different response structure
- Be natural and conversational, not literary

FORBIDDEN: "That said," "However," "On the other hand," "Overall," "Ultimately," "At the end of the day," "Game-changer," "Double-edged sword," "throwing a wrench," "well-oiled machine," "like," metaphors, analogies

Create a system prompt for natural, motivated responses.`

    // Call OpenAI API
    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${openaiApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'gpt-4.1-2025-04-14',
        messages: [
          {
            role: 'user',
            content: analysisPrompt
          }
        ],
        temperature: 0.7,
        max_tokens: 1500
      }),
    })

    if (!response.ok) {
      const errorData = await response.json()
      throw new Error(`OpenAI API error: ${errorData.error?.message || response.statusText}`)
    }

    const data = await response.json()
    const systemPrompt = data.choices[0]?.message?.content

    if (!systemPrompt) {
      throw new Error('No system prompt generated by OpenAI')
    }

    console.log(`✅ OpenAI trait analysis completed for ${name}`)

    return new Response(JSON.stringify({
      success: true,
      system_prompt: systemPrompt,
      persona_name: name,
      model_used: 'gpt-4.1-2025-04-14'
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })

  } catch (error) {
    console.error('Error in v4-openai-trait-analyzer:', error)
    return new Response(JSON.stringify({
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  }
})