import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

const openaiApiKey = Deno.env.get('OPENAI_API_KEY')
const supabaseUrl = Deno.env.get('SUPABASE_URL')!
const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  try {
    const { persona_id, user_message, conversation_history } = await req.json()

    if (!persona_id || !user_message) {
      throw new Error('Missing required parameters: persona_id and user_message')
    }

    // Initialize Supabase client
    const supabase = createClient(supabaseUrl, supabaseServiceKey)

    // Fetch the full persona profile
    const { data: persona, error } = await supabase
      .from('v4_personas')
      .select('*')
      .eq('persona_id', persona_id)
      .single()

    if (error || !persona) {
      throw new Error(`Persona not found: ${persona_id}`)
    }

    // Extract demographics for context
    const demographics = persona.conversation_summary?.demographics || {}
    const name = demographics.name || persona.name || 'Unknown'
    const age = demographics.age || 'unknown age'
    const occupation = demographics.occupation || 'unknown occupation'
    const location = demographics.location || 'unknown location'

    // Prepare the OpenAI analysis prompt
    const analysisPrompt = `You are an expert personality analyst tasked with creating a comprehensive conversation system prompt for an AI persona based on their full psychological profile and the user's question.

PERSONA PROFILE:
Name: ${name}
Age: ${age}
Occupation: ${occupation}
Location: ${location}

FULL PERSONALITY DATA:
${JSON.stringify(persona.full_profile, null, 2)}

USER'S QUESTION: "${user_message}"

CONVERSATION HISTORY: ${JSON.stringify(conversation_history || [], null, 2)}

Your task is to analyze this persona's complete psychological profile and create a specific, contextual system prompt that will guide the AI's response to this exact question. 

Analyze:
1. Which personality traits, motivations, biases, and characteristics are most relevant to answering this specific question
2. What stance/opinion this person would have based on their psychological makeup
3. How they would express themselves given their communication style, background, and emotional patterns

Generate a complete system prompt that includes:

1. IDENTITY CONTEXT: Brief reminder of who they are
2. RELEVANT TRAITS: The 5-8 most relevant psychological traits from their profile that apply to this question
3. STANCE/OPINION: Their specific viewpoint on this topic based on their traits
4. COMMUNICATION STYLE: How they would express this based on their personality
5. RESPONSE GUIDELINES: Specific instructions for tone, approach, and perspective

Return ONLY the system prompt text, nothing else. Make it natural and human-like, not robotic. The prompt should guide the AI to respond as this specific person would, with their unique perspective and voice.`

    // Call OpenAI API
    const response = await fetch('https://api.openai.com/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${openaiApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: 'gpt-4.1-2025-04-14',
        messages: [
          {
            role: 'user',
            content: analysisPrompt
          }
        ],
        temperature: 0.7,
        max_tokens: 1500
      }),
    })

    if (!response.ok) {
      const errorData = await response.json()
      throw new Error(`OpenAI API error: ${errorData.error?.message || response.statusText}`)
    }

    const data = await response.json()
    const systemPrompt = data.choices[0]?.message?.content

    if (!systemPrompt) {
      throw new Error('No system prompt generated by OpenAI')
    }

    console.log(`✅ OpenAI trait analysis completed for ${name}`)

    return new Response(JSON.stringify({
      success: true,
      system_prompt: systemPrompt,
      persona_name: name,
      model_used: 'gpt-4.1-2025-04-14'
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })

  } catch (error) {
    console.error('Error in v4-openai-trait-analyzer:', error)
    return new Response(JSON.stringify({
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  }
})