
export const personaTemplate = {
  persona_id: '',
  name: '',
  creation_date: '',
  metadata: {
    age: null,
    gender: null,
    race_ethnicity: null,
    region: null,
    location_history: {
      grew_up_in: null,
      current_residence: null,
    },
    income_level: null,
    education_level: null,
    occupation: null,
    relationship_status: null,
    children_or_caregiver: null,
    cultural_background: null,
    disabilities_or_conditions: null,
    family_medical_history: null,
  },
  trait_profile: {
    big_five: {},
    moral_foundations: {},
    world_values: {},
    political_compass: {},
    behavioral_economics: {},
    extended_traits: {},
  },
  behavioral_modulation: {
    cognitive_load_pattern: "mid_to_high_variability",
    attention_regulation: "context_sensitive",
    emotional_reactivity: "medium_high",
    stress_behavior: "defensive_creativity",
    fatigue_pattern: "cyclical",
    physical_health_consideration: "mild_hormonal_sensitivity",
    trust_behavior_under_strain: "selective_mirroring",
    coping_mechanisms: "info_loops_and_isolation",
  },
  linguistic_profile: {
    default_output_length: "moderate",
    speech_register: "hybrid",
    regional_influence: null,
    professional_or_educational_influence: null,
    cultural_speech_patterns: null,
    generational_or_peer_influence: null,
    speaking_style: {
      uses_neutral_fillers: true,
      sentence_revisions: true,
      contradiction_tolerance: true,
      mirroring_tendency: true,
      verbosity_by_topic: {
        work: "long",
        politics: "moderate",
        relationships: "short",
        health: "fluctuates",
      },
      speech_irregularity_patterns: {
        restart_phrases: true,
        trailing_off: true,
        intensity_swings: true,
      },
    },
    sample_phrasing: [],
  },
  preinterview_tags: [],
  simulation_directives: {
    encourage_contradiction: true,
    emotional_asymmetry: true,
    stress_behavior_expected: true,
    inconsistency_is_valid: true,
    response_length_variability: true,
  },
};

