import { serve } from "https://deno.land/std@0.168.0/http/server.ts"
import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'

const corsHeaders = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

const grokApiKey = Deno.env.get('GROK_API_KEY')
const supabaseUrl = Deno.env.get('SUPABASE_URL')!
const supabaseServiceKey = Deno.env.get('SUPABASE_SERVICE_ROLE_KEY')!
const GROK_MODEL = Deno.env.get("GROK_MODEL") ?? "grok-4-latest"

console.log(`🔥 DEPLOYMENT TEST - Edge function is live and updated!`)

serve(async (req) => {
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: corsHeaders })
  }

  try {
    const { persona_id, user_message, conversation_history } = await req.json()
    
    console.log(`1. FUNCTION START - persona_id: ${persona_id}`)

    if (!persona_id || !user_message) {
      throw new Error('Missing required parameters: persona_id and user_message')
    }

    // Initialize Supabase client
    const supabase = createClient(supabaseUrl, supabaseServiceKey)

    console.log(`2. CALLING OPENAI TRAIT ANALYZER`)

    // Step 1: Get OpenAI trait analysis and system prompt
    const { data: analysisData, error: analysisError } = await supabase.functions.invoke('v4-openai-trait-analyzer', {
      body: {
        persona_id,
        user_message,
        conversation_history
      }
    })

    if (analysisError) {
      console.error('❌ Error calling OpenAI trait analyzer:', analysisError)
      throw new Error(`Trait analysis failed: ${analysisError.message}`)
    }

    if (!analysisData?.success || !analysisData?.system_prompt) {
      console.error('❌ No system prompt generated')
      throw new Error('Failed to generate system prompt')
    }

    console.log(`3. OPENAI ANALYSIS COMPLETE - Generated system prompt`)
    console.log(`4. CALLING GROK WITH OPENAI-GENERATED PROMPT`)

    // Step 2: Call Grok with the OpenAI-generated system prompt
    const grokMessages = [
      {
        role: "system",
        content: analysisData.system_prompt
      }
    ]

    // Add conversation history
    if (conversation_history && conversation_history.length > 0) {
      grokMessages.push(...conversation_history)
    }

    // Add current user message
    grokMessages.push({
      role: "user",
      content: user_message
    })

    const grokResponse = await fetch('https://api.x.ai/v1/chat/completions', {
      method: 'POST',
      headers: {
        'Authorization': `Bearer ${grokApiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model: GROK_MODEL,
        messages: grokMessages,
        temperature: 0.8,
        max_tokens: 2000
      }),
    })

    if (!grokResponse.ok) {
      const errorData = await grokResponse.json()
      console.error('❌ Grok API error:', errorData)
      throw new Error(`Grok API error: ${errorData.error?.message || grokResponse.statusText}`)
    }

    const grokData = await grokResponse.json()
    const grokMessage = grokData.choices[0]?.message?.content

    if (!grokMessage) {
      console.error('❌ No response from Grok')
      throw new Error('No response generated by Grok')
    }

    console.log(`5. GROK RESPONSE RECEIVED`)
    console.log(`✅ PIPELINE COMPLETE - OpenAI→Grok successful`)

    // Log the Grok prompt for monitoring
    try {
      await supabase.functions.invoke('log-grok-prompt', {
        body: {
          source: 'v4-grok-conversation',
          persona_id,
          persona_name: analysisData.persona_name,
          user_message,
          system_instructions: analysisData.system_prompt,
          conversation_history,
          extra: {
            grok_model: GROK_MODEL,
            analysis_model: analysisData.model_used,
            traits_selected: analysisData.traits_selected
          }
        }
      })
    } catch (logError) {
      console.error('Failed to log Grok prompt:', logError)
      // Don't fail the main request if logging fails
    }

    // Return the Grok response directly (no post-processing)
    return new Response(JSON.stringify({
      success: true,
      response: grokMessage,
      persona_name: analysisData.persona_name,
      model_used: GROK_MODEL,
      analysis_model: analysisData.model_used
    }), {
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })

  } catch (error) {
    console.error('❌ Error in v4-grok-conversation:', error)
    return new Response(JSON.stringify({
      success: false,
      error: error instanceof Error ? error.message : 'Unknown error'
    }), {
      status: 500,
      headers: { ...corsHeaders, 'Content-Type': 'application/json' },
    })
  }
})