
import { DbPersona, Persona, PersonaMetadata, InterviewSection } from "./types";
import { Json } from "@/integrations/supabase/types";

export function personaToDbPersona(persona: Persona): Omit<DbPersona, 'id' | 'created_at'> {
  console.log("Converting persona to DB format:", persona.persona_id);
  
  // Only include fields that exist as columns in the database
  // Exclude 'id' and 'created_at' as they are generated by the database
  const dbPersona: Omit<DbPersona, 'id' | 'created_at'> = {
    persona_id: persona.persona_id,
    name: persona.name,
    creation_date: persona.creation_date,
    prompt: persona.prompt || null,
    metadata: persona.metadata as unknown as Json,
    trait_profile: persona.trait_profile as unknown as Json,
    behavioral_modulation: persona.behavioral_modulation as unknown as Json,
    linguistic_profile: persona.linguistic_profile as unknown as Json,
    preinterview_tags: persona.preinterview_tags as unknown as Json,
    simulation_directives: persona.simulation_directives as unknown as Json,
    interview_sections: persona.interview_sections as unknown as Json,
    emotional_triggers: persona.emotional_triggers ? persona.emotional_triggers as unknown as Json : null,
    is_public: persona.is_public || false,
    user_id: persona.user_id,
    profile_image_url: persona.profile_image_url || null,
    enhanced_metadata_version: persona.enhanced_metadata_version || 2,
  };
  
  console.log("DB persona ready for insert:", {
    persona_id: dbPersona.persona_id,
    name: dbPersona.name,
    has_emotional_triggers: !!dbPersona.emotional_triggers,
    enhanced_metadata_version: dbPersona.enhanced_metadata_version,
    trait_profile_keys: dbPersona.trait_profile ? Object.keys(dbPersona.trait_profile as any) : []
  });
  
  return dbPersona;
}

export function dbPersonaToPersona(dbPersona: DbPersona): Persona {
  console.log("Converting DB persona to app format:", dbPersona.persona_id);
  
  // Handle trait profile data more carefully with comprehensive validation
  let traitProfile = dbPersona.trait_profile as unknown as Record<string, any>;
  
  // Check for various forms of malformed trait data
  if (!traitProfile || 
      typeof traitProfile !== 'object' || 
      traitProfile._type === "undefined" || 
      traitProfile.value === "undefined" ||
      Object.keys(traitProfile).length === 0) {
    
    console.warn("Trait profile data is malformed or empty, creating comprehensive default structure");
    traitProfile = createDefaultTraitProfile();
  } else {
    // Validate existing trait profile structure
    traitProfile = validateTraitProfile(traitProfile);
  }
  
  return {
    id: dbPersona.id,
    persona_id: dbPersona.persona_id,
    name: dbPersona.name,
    creation_date: dbPersona.creation_date,
    prompt: dbPersona.prompt || "",
    metadata: dbPersona.metadata as unknown as PersonaMetadata,
    trait_profile: traitProfile,
    behavioral_modulation: dbPersona.behavioral_modulation as unknown as Record<string, any>,
    linguistic_profile: dbPersona.linguistic_profile as unknown as Record<string, any>,
    preinterview_tags: dbPersona.preinterview_tags as unknown as string[],
    simulation_directives: dbPersona.simulation_directives as unknown as Record<string, any>,
    interview_sections: dbPersona.interview_sections as unknown as InterviewSection[] | {
      interview_sections: InterviewSection[];
    },
    emotional_triggers: dbPersona.emotional_triggers as unknown as any || {
      positive_triggers: [],
      negative_triggers: []
    },
    is_public: dbPersona.is_public || false,
    user_id: dbPersona.user_id,
    profile_image_url: dbPersona.profile_image_url || null,
    enhanced_metadata_version: dbPersona.enhanced_metadata_version || 2,
    created_at: dbPersona.created_at,
    // Add missing required properties with defaults
    persona_context: {},
    persona_type: "generated",
  };
}

function createDefaultTraitProfile() {
  return {
    big_five: {
      openness: 0.5,
      conscientiousness: 0.5,
      extraversion: 0.5,
      agreeableness: 0.5,
      neuroticism: 0.5,
    },
    moral_foundations: {
      care: 0.5,
      fairness: 0.5,
      loyalty: 0.5,
      authority: 0.5,
      sanctity: 0.5,
      liberty: 0.5,
    },
    world_values: {
      traditional_vs_secular: 0.5,
      survival_vs_self_expression: 0.5,
      materialist_vs_postmaterialist: 0.5,
    },
    political_compass: {
      economic: 0.5,
      authoritarian_libertarian: 0.5,
      cultural_conservative_progressive: 0.5,
      political_salience: 0.5,
      group_fusion_level: 0.5,
      outgroup_threat_sensitivity: 0.5,
      commons_orientation: 0.5,
      political_motivations: {
        material_interest: 0.5,
        moral_vision: 0.5,
        cultural_preservation: 0.5,
        status_reordering: 0.5,
      },
    },
    cultural_dimensions: {
      power_distance: 0.5,
      individualism_vs_collectivism: 0.5,
      masculinity_vs_femininity: 0.5,
      uncertainty_avoidance: 0.5,
      long_term_orientation: 0.5,
      indulgence_vs_restraint: 0.5,
    },
    social_identity: {
      identity_strength: 0.5,
      identity_complexity: 0.5,
      ingroup_bias_tendency: 0.5,
      outgroup_bias_tendency: 0.5,
      social_dominance_orientation: 0.5,
      system_justification: 0.5,
      intergroup_contact_comfort: 0.5,
      cultural_intelligence: 0.5,
    },
    behavioral_economics: {
      present_bias: 0.5,
      loss_aversion: 0.5,
      overconfidence: 0.5,
      risk_sensitivity: 0.5,
      scarcity_sensitivity: 0.5,
    },
    extended_traits: {
      truth_orientation: 0.5,
      moral_consistency: 0.5,
      self_awareness: 0.5,
      empathy: 0.5,
      self_efficacy: 0.5,
      manipulativeness: 0.5,
      impulse_control: 0.5,
      shadow_trait_activation: 0.5,
      attention_pattern: 0.5,
      cognitive_load_resilience: 0.5,
      institutional_trust: 0.5,
      conformity_tendency: 0.5,
      conflict_avoidance: 0.5,
      cognitive_flexibility: 0.5,
      need_for_cognitive_closure: 0.5,
      emotional_intensity: 0.5,
      emotional_regulation: 0.5,
      trigger_sensitivity: 0.5,
    },
  };
}

function validateTraitProfile(traitProfile: Record<string, any>) {
  const defaultProfile = createDefaultTraitProfile();
  
  // Ensure all main categories exist and have proper values
  for (const [category, defaultValues] of Object.entries(defaultProfile)) {
    if (!traitProfile[category] || typeof traitProfile[category] !== 'object') {
      console.warn(`Missing trait category: ${category}, using defaults`);
      traitProfile[category] = defaultValues;
    } else {
      // Validate individual traits within each category
      for (const [trait, defaultValue] of Object.entries(defaultValues as any)) {
        if (typeof defaultValue === 'object') {
          // Handle nested objects like political_motivations
          if (!traitProfile[category][trait] || typeof traitProfile[category][trait] !== 'object') {
            traitProfile[category][trait] = defaultValue;
          } else {
            for (const [nestedTrait, nestedDefault] of Object.entries(defaultValue)) {
              if (typeof traitProfile[category][trait][nestedTrait] !== 'number' ||
                  traitProfile[category][trait][nestedTrait] < 0 ||
                  traitProfile[category][trait][nestedTrait] > 1) {
                traitProfile[category][trait][nestedTrait] = nestedDefault;
              }
            }
          }
        } else {
          // Handle regular numeric traits
          if (typeof traitProfile[category][trait] !== 'number' ||
              traitProfile[category][trait] < 0 ||
              traitProfile[category][trait] > 1) {
            console.warn(`Invalid trait value for ${category}.${trait}, using default`);
            traitProfile[category][trait] = defaultValue;
          }
        }
      }
    }
  }
  
  return traitProfile;
}
