// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eszusrcpsdzlnslewtws.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzenVzcmNwc2R6bG5zbGV3dHdzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4NjI2MzQsImV4cCI6MjA2MzQzODYzNH0.cG_mSgHZpxFQYG6NBy-OiYUmimF9nWY552sApC9u6FI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);